<?php /** @var Sy_Action_Model_Action $_ad */ ?>
<?php if ($_ad = $this->getActionDetails()) : ?>

<div class="widget">
    <div class="action-details">
        <div style="float: left; margin: 0 20px 20px 0;"><img src="<?php echo $_ad->getResizedImage(); ?>" alt="<?php echo $_ad->getName(); ?>" /></div>
        <h1><?php echo $_ad->getName(); ?></h1>
        <div><?php echo $_ad->getDescription(); ?></div>
        <br><hr><br>
        <div>
            <b>Action Duration: </b> <?php echo $_ad->getDuration(); ?>
        </div>
    </div>
    <div style="clear:both;"></div>
    <br>
    <hr>
    <br>
    <div class="widget-products">
        <h3>Action Products</h3>
        <?php /** @var Sy_Action_Model_Action $_aps */ ?>
        <?php if ($_aps = $this->getActionProducts()) : ?>
        <ul class="products-grid products-grid--max-6-col first last odd">
        <?php foreach ($_aps as $_ap) : ?>
                <li class="item action-item">
                    <a href="<?php echo $_ap->getProductUrl() ?>" title="<?php echo $this->stripTags($_ap->getName(), null, true) ?>" class="product-image">
                        <img src="<?php echo $this->helper('catalog/image')->init($_ap, 'small_image')->resize(200) ?>" alt="<?php echo $this->stripTags($_ap->getName(), null, true) ?>" />
                    </a>
                    <div class="product-info">
                        <h3 class="product-name"><a href="<?php echo $_ap->getProductUrl() ?>" title="<?php echo $this->stripTags($_ap->getName(), null, true) ?>"><?php echo $this->helper('catalog/output')->productAttribute($_ap, $_ap->getName() , 'name') ?></a></h3>
                        <div class="product-sku"><?php echo $_ap->sku; ?></div>
                        <div class="product-price"><?php echo $this->getPriceHtml($_ap, true, '-widget-new-grid'); ?></div>
                    </div>
                </li>
        <?php endforeach; ?>
        </ul>
        <?php endif; ?>
    </div>
</div>

<?php endif; ?>