<?php echo $this->getPagerHtml(); ?>

<?php /** @var Sy_Action_Model_Action $_actions */ ?>
<?php if ($_actions = $this->getActionsList()) : ?>
    <div class="widget widget-actions">
    <div class="widget-title">
        <h2>Module SY Actions List</h2>
    </div>
    <ul class="products-grid">
    <?php foreach ($_actions as $_action) : ?>
        <li class="item action-item">
            <a href="<?php echo Mage::getBaseUrl() . 'actions/action/index/id/' . $_action->getId(); ?>" title="<?php echo $_action->getName(); ?>" class="action-image">
                <img src="<?php echo $_action->getResizedImage(); ?>" alt="<?php echo $_action->getName(); ?>" />
            </a>
            <div class="action-info">
                <h3 class="action-name">
                    <a href="<?php echo Mage::getBaseUrl() . 'actions/action/index/id/' . $_action->getId(); ?>" title="<?php echo $_action->getName(); ?>">
                        <?php echo $_action->getName(); ?>
                    </a>
                </h3>
                <p><?php echo $_action->getDuration(); ?></p>
            </div>
        </li>
    <?php endforeach; ?>
    </ul>
</div>
<?php endif; ?>
