<?php /** @var Sy_Action_Model_Action $_actions */ ?>
<?php if ($_actions = $this->getActionsByProduct()) : ?>

    <h3>Product in Actions</h3>

    <?php foreach ($_actions as $_pa) : ?>
    <div class="item f-left">
        <div class="action-image">
            <img src="<?php echo $_pa->getResizedImage(); ?>" alt="<?php echo $_pa->getName(); ?>" />
        </div>
        <b><?php echo $_pa->getName(); ?></b>
        <div>
            <b>Action Duration: </b><?php echo $_pa->getDuration(); ?>
        </div>
        <div class="action-details">
            <a href="<?php echo Mage::getBaseUrl().'actions/action/index/id/'.$_pa->getId(); ?>" title="<?php echo $_pa->getName(); ?>">Action details...</a>
        </div>
    </div>
    <?php endforeach; ?>
<?php endif; ?>
